[project]
name = "KubePy-Hound"
version = "0.1.0"
description = "A BloodHound k8s resource collector"
readme = "README.md"
dependencies = [
    "duckdb>=1.3.2",
    "kubernetes>=33.1.0",
    "pydantic>=2.11.9",
    "pyyaml>=6.0.2",
    "typer>=0.17.4",
]
